cmake_minimum_required(VERSION 3.8)

set(PLATFORM_XOS_HOST "Xbox-HostOS")
set(PLATFORM_XOS_SRA "Xbox-SystemOS")
set(PLATFORM_XOS_ERA "Xbox-EraOS")

# Determine our target XOS
# By default; we assume System OS
set(PLATFORM_OS ${PLATFORM_XOS_SRA})

# Setup output directories
set(BINARY_OUTPUT_DIR ${PROJECT_SOURCE_DIR}/Binaries/${PLATFORM_OS})
set(LIBRARY_OUTPUT_DIR ${PROJECT_SOURCE_DIR}/Lib/${PLATFORM_OS})

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BINARY_OUTPUT_DIR}/${CMAKE_BUILD_TYPE}/)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BINARY_OUTPUT_DIR}/${CMAKE_BUILD_TYPE}/)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${BINARY_OUTPUT_DIR}/${CMAKE_BUILD_TYPE}/)